# Analyse Exploratoire

### Import des modules

In [16]:
# Bibliothèques
import pandas as pd

### Import des données

In [17]:
# On importe les données
building_consumption = pd.read_csv("./sources/2016_Building_Energy_Benchmarking.csv")

### Analyse Exploratoire

In [18]:
# On regarde comment un batiment est défini dans ce jeu de données 
display(building_consumption.head())
# On affiche les 5 premieres lignes du jeu de données avec toute les colonnes*
display(building_consumption.head().T)

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3946027.0,12764.52930,1276453.0,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3242851.0,51450.81641,5145082.0,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,49526664.0,14938.00000,1493800.0,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,8.115253e+05,2768924.0,18112.13086,1811213.0,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,1.573449e+06,5368607.0,88039.98438,8803998.0,False,NaN,Compliant,NaN,505.01,2.88

,0,1,2,3,4
OSEBuildingID,1,2,3,5,8
DataYear,2016,2016,2016,2016,2016
BuildingType,NonResidential,NonResidential,NonResidential,NonResidential,NonResidential
PrimaryPropertyType,Hotel,Hotel,Hotel,Hotel,Hotel
PropertyName,Mayflower park hotel,Paramount Hotel,5673-The Westin Seattle,HOTEL MAX,WARWICK SEATTLE HOTEL (ID8)
Address,405 Olive way,724 Pine street,1900 5th Avenue,620 STEWART ST,401 LENORA ST
City,Seattle,Seattle,Seattle,Seattle,Seattle
State,WA,WA,WA,WA,WA
ZipCode,98101.0,98101.0,98101.0,98101.0,98121.0
TaxParcelIdentificationNumber,0659000030,0659000220,0659000475,0659000640,0659000970
CouncilDistrictCode,7,7,7,7,7
Neighborhood,DOWNTOWN,DOWNTOWN,DOWNTOWN,DOWNTOWN,DOWNTOWN
Latitude,47.6122,47.61317,47.61393,47.61412,47.61375
Longitude,-122.33799,-122.33393,-122.3381,-122.33664,-122.34047
YearBuilt,1927,1996,1969,1926,1980
NumberofBuildings,1.0,1.0,1.0,1.0,1.0
NumberofFloors,12,11,41,10,18
PropertyGFATotal,88434,103566,956110,61320,175580
PropertyGFAParking,0,15064,196718,0,62000
PropertyGFABuilding(s),88434,88502,759392,61320,113580
ListOfAllPropertyUseTypes,Hotel,"Hotel, Parking, Restaurant",Hotel,Hotel,"Hotel, Parking, Swimming Pool"
LargestPropertyUseType,Hotel,Hotel,Hotel,Hotel,Hotel
LargestPropertyUseTypeGFA,88434.0,83880.0,756493.0,61320.0,123445.0
SecondLargestPropertyUseType,NaN,Parking,NaN,NaN,Parking
SecondLargestPropertyUseTypeGFA,NaN,15064.0,NaN,NaN,68009.0
ThirdLargestPropertyUseType,NaN,Restaurant,NaN,NaN,Swimming Pool
ThirdLargestPropertyUseTypeGFA,NaN,4622.0,NaN,NaN,0.0
YearsENERGYSTARCertified,NaN,NaN,NaN,NaN,NaN
ENERGYSTARScore,60.0,61.0,43.0,56.0,75.0
SiteEUI(kBtu/sf),81.699997,94.800003,96.0,110.800003,114.800003
SiteEUIWN(kBtu/sf),84.300003,97.900002,97.699997,113.300003,118.699997
SourceEUI(kBtu/sf),182.5,176.100006,241.899994,216.199997,211.399994
SourceEUIWN(kBtu/sf),189.0,179.399994,244.100006,224.0,215.600006
SiteEnergyUse(kBtu),7226362.5,8387933.0,72587024.0,6794584.0,14172606.0
SiteEnergyUseWN(kBtu),7456910.0,8664479.0,73937112.0,6946800.5,14656503.0
SteamUse(kBtu),2003882.0,0.0,21566554.0,2214446.25,0.0
Electricity(kWh),1156514.25,950425.1875,14515435.0,811525.3125,1573448.625
Electricity(kBtu),3946027.0,3242851.0,49526664.0,2768924.0,5368607.0
NaturalGas(therms),12764.5293,51450.81641,14938.0,18112.13086,88039.98438
NaturalGas(kBtu),1276453.0,5145082.0,1493800.0,1811213.0,8803998.0
DefaultData,False,False,False,False,False
Comments,NaN,NaN,NaN,NaN,NaN
ComplianceStatus,Compliant,Compliant,Compliant,Compliant,Compliant
Outlier,NaN,NaN,NaN,NaN,NaN
TotalGHGEmissions,249.98,295.86,2089.28,286.43,505.01
GHGEmissionsIntensity,2.83,2.86,2.19,4.67,2.88

In [19]:
# On affiche toute les valeurs unique de la colonne 'Outlier' pour comprendre son utilité
outlier_values = building_consumption['Outlier'].unique()
print("Valeurs uniques dans la colonne 'Outlier' :")
for value in outlier_values:
    print(f"- {value}")

Valeurs uniques dans la colonne 'Outlier' :
- nan
- High outlier
- Low outlier

In [20]:
# On regarde le nombre de valeurs manquantes par colonne ainsi que leur type 
print(f"Nombre de lignes : {building_consumption.shape[0]}")
print(f"Nombre de colonnes : {building_consumption.shape[1]}")
print("\nListe des colonnes :")
building_consumption.info(verbose=True)

Nombre de lignes : 3376
Nombre de colonnes : 46

Liste des colonnes :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3376 entries, 0 to 3375
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   OSEBuildingID                    3376 non-null   int64
 1   DataYear                         3376 non-null   int64
 2   BuildingType                     3376 non-null   object
 3   PrimaryPropertyType              3376 non-null   object
 4   PropertyName                     3376 non-null   object
 5   Address                          3376 non-null   object
 6   City                             3376 non-null   object
 7   State                            3376 non-null   object
 8   ZipCode                          3360 non-null   float64
 9   TaxParcelIdentificationNumber    3376 non-null   object
 10  CouncilDistrictCode              3376 non-null   int64
 11  Neighborhood                     3376 non-null   object
 12  Latitude                         3376 non-null   float64
 13  Longitude                        3376 non-null   float64
 14  YearBuilt                        3376 non-null   int64
 15  NumberofBuildings                3368 non-null   float64
 16  NumberofFloors                   3376 non-null   int64
 17  PropertyGFATotal                 3376 non-null   int64
 18  PropertyGFAParking               3376 non-null   int64
 19  PropertyGFABuilding(s)           3376 non-null   int64
 20  ListOfAllPropertyUseTypes        3367 non-null   object
 21  LargestPropertyUseType           3356 non-null   object
 22  LargestPropertyUseTypeGFA        3356 non-null   float64
 23  SecondLargestPropertyUseType     1679 non-null   object
 24  SecondLargestPropertyUseTypeGFA  1679 non-null   float64
 25  ThirdLargestPropertyUseType      596 non-null    object
 26  ThirdLargestPropertyUseTypeGFA   596 non-null    float64
 27  YearsENERGYSTARCertified         119 non-null    object
 28  ENERGYSTARScore                  2533 non-null   float64
 29  SiteEUI(kBtu/sf)                 3369 non-null   float64
 30  SiteEUIWN(kBtu/sf)               3370 non-null   float64
 31  SourceEUI(kBtu/sf)               3367 non-null   float64
 32  SourceEUIWN(kBtu/sf)             3367 non-null   float64
 33  SiteEnergyUse(kBtu)              3371 non-null   float64
 34  SiteEnergyUseWN(kBtu)            3370 non-null   float64
 35  SteamUse(kBtu)                   3367 non-null   float64
 36  Electricity(kWh)                 3367 non-null   float64
 37  Electricity(kBtu)                3367 non-null   float64
 38  NaturalGas(therms)               3367 non-null   float64
 39  NaturalGas(kBtu)                 3367 non-null   float64
 40  DefaultData                      3376 non-null   bool
 41  Comments                         0 non-null      float64
 42  ComplianceStatus                 3376 non-null   object
 43  Outlier                          32 non-null     object
 44  TotalGHGEmissions                3367 non-null   float64
 45  GHGEmissionsIntensity            3367 non-null   float64
dtypes: bool(1), float64(22), int64(8), object(15)
memory usage: 1.2+ MB

#### TERMINER L'ANALYSE EXPLORATOIRE

A réaliser : 
- Une analyse descriptive des données, y compris une explication du sens des colonnes gardées, des arguments derrière la suppression de lignes ou de colonnes, des statistiques descriptives et des visualisations pertinentes.

### 1- On commence par ne garder que les batiments non résidentiels

Ce dataset contient des informations sur la consommation énergétique de bâtiments en 2016. 

**Focus de l'analyse :** Nous nous concentrons uniquement sur les **bâtiments non résidentiels** (commerciaux, bureaux, industriels, etc.) pour analyser leur consommation énergétique et identifier les opportunités d'optimisation.

In [21]:
 # On affiche tout les Builkding Type disponibles
building_types = building_consumption['PrimaryPropertyType'].unique()
print("Types de bâtiments disponibles :")
for b_type in building_types:
    print(f"- {b_type}")

Types de bâtiments disponibles :
- Hotel
- Other
- Mid-Rise Multifamily
- Mixed Use Property
- K-12 School
- University
- Small- and Mid-Sized Office
- Self-Storage Facility
- Warehouse
- Large Office
- Senior Care Community
- Medical Office
- Retail Store
- Hospital
- Residence Hall
- Distribution Center
- Worship Facility
- Low-Rise Multifamily
- Supermarket / Grocery Store
- Laboratory
- Refrigerated Warehouse
- Restaurant
- High-Rise Multifamily
- Office

In [22]:
# Filtrer pour ne garder que les bâtiments non résidentiels
print(f"Nombre total de bâtiments avant filtrage : {len(building_consumption)}")
initial_count = len(building_consumption)

# Identifier les types résidentiels à exclure
residential_types = [
    'Multifamily LR (1-4)',
    'Multifamily MR (5-9)', 
    'Multifamily HR (10+)',
    'Campus',
    'Residential',
    'Multifamily Housing',
    'Senior Care Community',
    'Residence Hall'
]

# Filtrer les bâtiments non résidentiels
if 'BuildingType' in building_consumption.columns:
    # Filtrer par BuildingType si disponible
    building_consumption = building_consumption[building_consumption['BuildingType'] == 'NonResidential'].copy()
    print(f"Nombre de bâtiments non résidentiels (BuildingType) : {len(building_consumption)}")
elif 'PrimaryPropertyType' in building_consumption.columns:
    # Sinon filtrer par PrimaryPropertyType dans le cas où BuildingType n'existe pas
    building_consumption = building_consumption[~building_consumption['PrimaryPropertyType'].isin(residential_types)].copy()
    print(f"Nombre de bâtiments non résidentiels (PrimaryPropertyType) : {len(building_consumption)}")

print(f"\nPourcentage conservé : {(len(building_consumption) / initial_count) * 100:.1f}%")

Nombre total de bâtiments avant filtrage : 3376
Nombre de bâtiments non résidentiels (BuildingType) : 1460

Pourcentage conservé : 43.2%

In [23]:
# Vérifier les types de bâtiments disponibles
print("Types de bâtiments disponibles :")
if 'BuildingType' in building_consumption.columns:
    print("\nBuildingType :")
    print(building_consumption['BuildingType'].value_counts())

if 'PrimaryPropertyType' in building_consumption.columns:
    print("\n\nPrimaryPropertyType (top 20) :")
    print(building_consumption['PrimaryPropertyType'].value_counts().head(20))

Types de bâtiments disponibles :

BuildingType :
BuildingType
NonResidential    1460
Name: count, dtype: int64


PrimaryPropertyType (top 20) :
PrimaryPropertyType
Small- and Mid-Sized Office    288
Other                          185
Warehouse                      180
Large Office                   168
Mixed Use Property             102
Retail Store                    91
Hotel                           76
Worship Facility                71
Distribution Center             51
Supermarket / Grocery Store     40
K-12 School                     39
Medical Office                  38
Self-Storage Facility           28
Residence Hall                  21
Senior Care Community           20
University                      17
Refrigerated Warehouse          12
Restaurant                      11
Hospital                        10
Laboratory                      10
Name: count, dtype: int64

### 2- On cherche ensuite les colonnes vides et sans intérets

In [24]:
# On affiche toutes les colonnes disponibles avec le pourcentage de valeurs manquantes
missing_data = building_consumption.isnull().sum().sort_values(ascending=False)
missing_percentage = (missing_data / building_consumption.shape[0]) * 100
missing_percentage = missing_percentage[missing_percentage > 0]
missing_percentage.sort_values(ascending=False, inplace=True) 
missing_percentage

Comments                           100.000000
Outlier                             98.972603
YearsENERGYSTARCertified            93.835616
ThirdLargestPropertyUseType         78.424658
ThirdLargestPropertyUseTypeGFA      78.424658
SecondLargestPropertyUseType        45.479452
SecondLargestPropertyUseTypeGFA     45.479452
ENERGYSTARScore                     31.849315
LargestPropertyUseTypeGFA            0.410959
LargestPropertyUseType               0.410959
SiteEUIWN(kBtu/sf)                   0.205479
SiteEUI(kBtu/sf)                     0.205479
SiteEnergyUseWN(kBtu)                0.205479
NumberofBuildings                    0.136986
Electricity(kBtu)                    0.136986
Electricity(kWh)                     0.136986
NaturalGas(kBtu)                     0.136986
NaturalGas(therms)                   0.136986
GHGEmissionsIntensity                0.136986
SteamUse(kBtu)                       0.136986
SourceEUIWN(kBtu/sf)                 0.136986
SourceEUI(kBtu/sf)                   0.136986
TotalGHGEmissions                    0.136986
SiteEnergyUse(kBtu)                  0.136986
ListOfAllPropertyUseTypes            0.136986
dtype: float64

In [25]:
# On affiche la quantité de batiment impacté par la colonne 'Outlier'
outlier_counts = building_consumption['Outlier'].value_counts()
print("Quantité de bâtiments impactés par la colonne 'Outlier' :")
for value, count in outlier_counts.items():
    print(f"- {value} : {count}")

# Nombre de bâtiments avant suppression des outliers
print(f"\nNombre de bâtiments AVANT suppression des outliers : {len(building_consumption)}")

# On supprime les batiments qui ont la colonne 'Outlier' renseignée
building_consumption = building_consumption[building_consumption['Outlier'].isna()].copy()

# Nombre de bâtiments après suppression des outliers
print(f"\nNombre de bâtiments APRÈS suppression des outliers : {len(building_consumption)}")

Quantité de bâtiments impactés par la colonne 'Outlier' :
- Low outlier : 13
- High outlier : 2

Nombre de bâtiments AVANT suppression des outliers : 1460

Nombre de bâtiments APRÈS suppression des outliers : 1445

In [26]:
# On supprime les colonnes qui ont plus de 40% de valeurs manquantes
threshold = 0.4 * len(building_consumption)
building_consumption = building_consumption.loc[:, building_consumption.isna().sum() < threshold]
print(f"\nNombre de colonnes après suppression de celles avec plus de 40% de valeurs manquantes : {building_consumption.shape[1]}")

# on affiche les colonnes restantes
building_consumption.info(verbose=True)

Nombre de colonnes après suppression de celles avec plus de 40% de valeurs manquantes : 39
<class 'pandas.core.frame.DataFrame'>
Index: 1445 entries, 0 to 3356
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   OSEBuildingID                  1445 non-null   int64
 1   DataYear                       1445 non-null   int64
 2   BuildingType                   1445 non-null   object
 3   PrimaryPropertyType            1445 non-null   object
 4   PropertyName                   1445 non-null   object
 5   Address                        1445 non-null   object
 6   City                           1445 non-null   object
 7   State                          1445 non-null   object
 8   ZipCode                        1445 non-null   float64
 9   TaxParcelIdentificationNumber  1445 non-null   object
 10  CouncilDistrictCode            1445 non-null   int64
 11  Neighborhood                   1445 non-null   object
 12  Latitude                       1445 non-null   float64
 13  Longitude                      1445 non-null   float64
 14  YearBuilt                      1445 non-null   int64
 15  NumberofBuildings              1443 non-null   float64
 16  NumberofFloors                 1445 non-null   int64
 17  PropertyGFATotal               1445 non-null   int64
 18  PropertyGFAParking             1445 non-null   int64
 19  PropertyGFABuilding(s)         1445 non-null   int64
 20  ListOfAllPropertyUseTypes      1443 non-null   object
 21  LargestPropertyUseType         1439 non-null   object
 22  LargestPropertyUseTypeGFA      1439 non-null   float64
 23  ENERGYSTARScore                985 non-null    float64
 24  SiteEUI(kBtu/sf)               1442 non-null   float64
 25  SiteEUIWN(kBtu/sf)             1442 non-null   float64
 26  SourceEUI(kBtu/sf)             1443 non-null   float64
 27  SourceEUIWN(kBtu/sf)           1443 non-null   float64
 28  SiteEnergyUse(kBtu)            1443 non-null   float64
 29  SiteEnergyUseWN(kBtu)          1442 non-null   float64
 30  SteamUse(kBtu)                 1443 non-null   float64
 31  Electricity(kWh)               1443 non-null   float64
 32  Electricity(kBtu)              1443 non-null   float64
 33  NaturalGas(therms)             1443 non-null   float64
 34  NaturalGas(kBtu)               1443 non-null   float64
 35  DefaultData                    1445 non-null   bool
 36  ComplianceStatus               1445 non-null   object
 37  TotalGHGEmissions              1443 non-null   float64
 38  GHGEmissionsIntensity          1443 non-null   float64
dtypes: bool(1), float64(19), int64(8), object(11)
memory usage: 441.7+ KB

### 3. Uniformisation des unités

On uniformise les valeurs et on renomme les colonnes avec les bonnes unités

In [27]:
# Convertion des KBtu en kWh pour uniformiser les unités énergétiques
building_consumption['SiteEnergyUse(kWh)'] = building_consumption['SiteEnergyUse(kBtu)'] * 0.29307107
building_consumption['SiteEUI(kWh/m2)'] = building_consumption['SiteEUI(kBtu/sf)'] * 3.2
building_consumption['NaturalGas(kWh)'] = building_consumption['NaturalGas(therms)'] * 29.3001

### 4. Explication des colonnes principales

Analysons les colonnes les plus pertinentes pour notre étude sur la consommation énergétique des bâtiments :

In [28]:
# Identification des types de colonnes
print("Types de données par catégorie :\n")

# Colonnes d'identification
id_cols = ['OSEBuildingID', 'DataYear', 'BuildingType', 'PrimaryPropertyType', 
           'PropertyName', 'TaxParcelIdentificationNumber', 'Location']
print(f"Colonnes d'identification ({len(id_cols)}) : {id_cols}\n")

# Colonnes de superficie
area_cols = [col for col in building_consumption.columns if 'floor' in col.lower() or 'area' in col.lower()]
print(f"Colonnes du nombre d'étages ({len(area_cols)}) : {area_cols}\n")

# Colonnes de consommation énergétique
energy_cols = [col for col in building_consumption.columns if 'energy' in col.lower() or 'EUI' in col or 'kBtu' in col]
print(f"Colonnes d'énergie ({len(energy_cols)}) : {energy_cols}\n")

# Colonnes d'émissions
emission_cols = [col for col in building_consumption.columns if 'emissions' in col.lower() or 'GHG' in col]
print(f"Colonnes d'émissions ({len(emission_cols)}) : {emission_cols}")

Types de données par catégorie :

Colonnes d'identification (7) : ['OSEBuildingID', 'DataYear', 'BuildingType', 'PrimaryPropertyType', 'PropertyName', 'TaxParcelIdentificationNumber', 'Location']

Colonnes du nombre d'étages (1) : ['NumberofFloors']

Colonnes d'énergie (12) : ['ENERGYSTARScore', 'SiteEUI(kBtu/sf)', 'SiteEUIWN(kBtu/sf)', 'SourceEUI(kBtu/sf)', 'SourceEUIWN(kBtu/sf)', 'SiteEnergyUse(kBtu)', 'SiteEnergyUseWN(kBtu)', 'SteamUse(kBtu)', 'Electricity(kBtu)', 'NaturalGas(kBtu)', 'SiteEnergyUse(kWh)', 'SiteEUI(kWh/m2)']

Colonnes d'émissions (2) : ['TotalGHGEmissions', 'GHGEmissionsIntensity']

### 4. Sélection des colonnes pertinentes

Pour notre analyse de la consommation énergétique, nous allons conserver les colonnes suivantes :

**Colonnes d'identification et caractérisation :**
- `OSEBuildingID` : Identifiant unique du bâtiment
- `BuildingType` : Type de bâtiment (résidentiel, commercial, etc.)
- `PrimaryPropertyType` : Sous-type plus précis du bâtiment
- `YearBuilt` : Année de construction (impact sur l'isolation et l'efficacité énergétique)

**Colonnes de superficie :**
- `PropertyGFATotal` : Surface totale du bâtiment en pieds carrés
- `PropertyGFABuilding(s)` : Surface des bâtiments
- `NumberofFloors(s)` : Nombre d'étages

**Colonnes de consommation énergétique :**
- `SiteEnergyUse(kBtu)` : Consommation énergétique totale sur site
- `SiteEUI(kBtu/sf)` : Intensité énergétique (consommation par surface)
- `Electricity(kWh)` : Consommation électrique
- `NaturalGas(therms)` : Consommation de gaz naturel

**Colonnes d'émissions :**
- `TotalGHGEmissions` : Émissions totales de gaz à effet de serre
- `GHGEmissionsIntensity` : Intensité des émissions

### 5. Nettoyage des données - Suppression des lignes et colonnes

- Suppression des lignes sans consommation énergétique (variable cible principale)
- Suppression des lignes sans surface (nécessaire pour calculer l'intensité énergétique)
- Élimination des valeurs nulles ou négatives (données aberrantes)

In [29]:
# Analyse des valeurs manquantes dans le dataset réduit
print("Valeurs manquantes par colonne :")
missing_analysis = pd.DataFrame({
    'Colonne': building_consumption.columns,
    'Valeurs_manquantes': building_consumption.isnull().sum().values,
    'Pourcentage': (building_consumption.isnull().sum().values / len(building_consumption) * 100).round(2)
})
print(missing_analysis.to_string(index=False))

print(f"\n\nNombre de lignes initial : {len(building_consumption)}")

# Suppression des lignes avec des valeurs manquantes critiques
# On supprime les lignes sans consommation énergétique (objectif principal)
building_consumption_clean = building_consumption.dropna(subset=['SiteEnergyUse(kBtu)'])
print(f"Après suppression des lignes sans SiteEnergyUse : {len(building_consumption_clean)}")

# Suppression des lignes sans surface (impossible de calculer l'intensité)
building_consumption_clean = building_consumption_clean.dropna(subset=['PropertyGFATotal'])
print(f"Après suppression des lignes sans PropertyGFATotal : {len(building_consumption_clean)}")

# Suppression des valeurs aberrantes (énergie ou surface = 0)
building_consumption_clean = building_consumption_clean[(building_consumption_clean['SiteEnergyUse(kBtu)'] > 0) & (building_consumption_clean['PropertyGFATotal'] > 0)]
print(f"Après suppression des valeurs nulles ou négatives : {len(building_consumption_clean)}")

# Suppression des colonnes qui nous intéressent pas pour l'analyse
columns_necessary = [
    'OSEBuildingID',
    'PrimaryPropertyType',
    'YearBuilt',
    'PropertyGFATotal',
    'PropertyGFABuilding(s)',
    'NumberofFloors',
    'SiteEnergyUse(kWh)',
    'SiteEUI(kWh/m2)',
    'Electricity(kWh)',
    'NaturalGas(kWh)',
    'TotalGHGEmissions',
    'GHGEmissionsIntensity'
]

# On ne garde que les colonnes intéressantes
building_consumption_clean = building_consumption_clean[columns_necessary].copy()

print(f"\nNombre final de colonnes : {building_consumption_clean.shape[1]}")
print(f"Nombre final de lignes : {building_consumption_clean.shape[0]}")

Valeurs manquantes par colonne :
                      Colonne  Valeurs_manquantes  Pourcentage
                OSEBuildingID                   0         0.00
                     DataYear                   0         0.00
                 BuildingType                   0         0.00
          PrimaryPropertyType                   0         0.00
                 PropertyName                   0         0.00
                      Address                   0         0.00
                         City                   0         0.00
                        State                   0         0.00
                      ZipCode                   0         0.00
TaxParcelIdentificationNumber                   0         0.00
          CouncilDistrictCode                   0         0.00
                 Neighborhood                   0         0.00
                     Latitude                   0         0.00
                    Longitude                   0         0.00
                    YearBuilt                   0         0.00
            NumberofBuildings                   2         0.14
               NumberofFloors                   0         0.00
             PropertyGFATotal                   0         0.00
           PropertyGFAParking                   0         0.00
       PropertyGFABuilding(s)                   0         0.00
    ListOfAllPropertyUseTypes                   2         0.14
       LargestPropertyUseType                   6         0.42
    LargestPropertyUseTypeGFA                   6         0.42
              ENERGYSTARScore                 460        31.83
             SiteEUI(kBtu/sf)                   3         0.21
           SiteEUIWN(kBtu/sf)                   3         0.21
           SourceEUI(kBtu/sf)                   2         0.14
         SourceEUIWN(kBtu/sf)                   2         0.14
          SiteEnergyUse(kBtu)                   2         0.14
        SiteEnergyUseWN(kBtu)                   3         0.21
               SteamUse(kBtu)                   2         0.14
             Electricity(kWh)                   2         0.14
            Electricity(kBtu)                   2         0.14
           NaturalGas(therms)                   2         0.14
             NaturalGas(kBtu)                   2         0.14
                  DefaultData                   0         0.00
             ComplianceStatus                   0         0.00
            TotalGHGEmissions                   2         0.14
        GHGEmissionsIntensity                   2         0.14
           SiteEnergyUse(kWh)                   2         0.14
              SiteEUI(kWh/m2)                   3         0.21
              NaturalGas(kWh)                   2         0.14


Nombre de lignes initial : 1445
Après suppression des lignes sans SiteEnergyUse : 1443
Après suppression des lignes sans PropertyGFATotal : 1443
Après suppression des valeurs nulles ou négatives : 1441

Nombre final de colonnes : 12
Nombre final de lignes : 1441

In [30]:
# On sauvegarde le jeu de données nettoyé
building_consumption_clean.to_csv("./sources/2016_Building_Energy_Benchmarking_01_cleaned.csv", index=False)

# On affiche les caractéristiques final du jeu de données nettoyé
display(building_consumption_clean.head().T)

,0,1,2,3,4
OSEBuildingID,1,2,3,5,8
PrimaryPropertyType,Hotel,Hotel,Hotel,Hotel,Hotel
YearBuilt,1927,1996,1969,1926,1980
PropertyGFATotal,88434,103566,956110,61320,175580
PropertyGFABuilding(s),88434,88502,759392,61320,113580
NumberofFloors,12,11,41,10,18
SiteEnergyUse(kWh),2117837.790083,2458260.499398,21273156.791796,1991296.003085,4153580.805108
SiteEUI(kWh/m2),261.43999,303.36001,307.2,354.56001,367.36001
Electricity(kWh),1156514.25,950425.1875,14515435.0,811525.3125,1573448.625
NaturalGas(kWh),374001.984943,1507514.065895,437684.8938,530687.245411,2579580.346332
TotalGHGEmissions,249.98,295.86,2089.28,286.43,505.01
GHGEmissionsIntensity,2.83,2.86,2.19,4.67,2.88

**Objectif du projet :** 
- Anticipez les besoins en consommation de bâtiments.

D'après mon analyse exploratoire, la cible (target) du machine learning devrait être **SiteEnergyUse(kBtu)** (kBtu = kilo-unités thermiques britanniques).

**Variable cible :**
- **SiteEnergyUse(kWh)** représente la consommation énergétique totale du bâtiment sur site : C'est une mesure directe et globale de la consommation

**Variables liées mais NON cibles :**
- **SiteEUI(kWh/m2)** = Intensité énergétique (dérivée de SiteEnergyUse / Surface)
- **Electricity(kWh)** = Composante partielle (seulement l'électricité)
- **NaturalGas(kWh)** = Composante partielle (seulement le gaz)
- **TotalGHGEmissions** = Conséquence de la consommation (pas la consommation elle-même)